name: Daily LinkedIn Post

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:


jobs:

  post:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20


    - name: Install Packages
      run: npm install


    - name: Run Automation
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}

      run: node script.js
